include:
  - project: sistema-administrativo/infra/ci-jobs
    ref: 5-possibilitar-testes-da-pipeline-em-modo-leitura
    file: 'gitlab-ci-backend.yml'
  - project: sistema-administrativo/infra/ci-jobs
    ref: 5-possibilitar-testes-da-pipeline-em-modo-leitura
    file: 'release-package-nexus.yml'
  - project: sistema-administrativo/infra/ci-jobs
    ref: 5-possibilitar-testes-da-pipeline-em-modo-leitura
    file: 'release-publish-docker.yml'

Release-Package-Nexus:
  extends: .Release-Package-Nexus
  stage: release

Publish-Imagem-Docker:
  extends: .Publish-Imagem-Docker
  stage: docker
  